name: update earthly built-in args list
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update-args:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install bs4 requests
      - run: python3 get-args.py
      - uses: stefanzweifel/git-auto-commit-action@v5