name: update earthly built-in args list
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update-args:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: python3 get-args.py
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0
      - run: earthly +echo
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update Earthfile